name: UWP
on: [pull_request]

jobs:
  run-windows-tests:
    name: Build & run tests
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout Code

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20'

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: 16.8

    - name: Resolve dependencies
      run: |
        Set-ExecutionPolicy Unrestricted -Scope Process -Force; 
        iex (New-Object System.Net.WebClient).DownloadString("https://aka.ms/rnw-vs2022-deps.ps1");

    - name: Install node modules
      run: yarn --frozen-lockfile

    - name: yarn build
      run:  yarn build

    - name: Run Windows x64 release
      run: npx react-native run-windows --arch x64 --release --logging

    # Workaround for a bug in package searching during deploy.
    # The deploy script only searches windows/{*/bin/x64/Release,Release/*}, but the build step above placed the pakcages at windows/x64/Release.
    # Copy the packages to Windows/Release before deploying.
    - name: Deploy
      shell: powershell
      run: |
        cd example
        Copy-Item -Path windows\x64\Release -Recurse -Destination windows\
        npx react-native run-windows --arch x64 --release --no-build --no-packager
